<?php

return [
    'fallback_experience_images' => [
        '/images/inisiatif/iklim-lanskap.jpg',
        '/images/inisiatif/konservasi-alam.jpg',
        '/images/inisiatif/pengembangan-masyarakat.jpg',
        '/images/inisiatif/riset-pengetahuan.jpg',
    ],
    'pillar_images' => [
        'KNOWLEDGE' => '/images/inisiatif/riset-pengetahuan.jpg',
        'NATURE' => '/images/inisiatif/konservasi-alam.jpg',
        'COMMUNITIES' => '/images/inisiatif/pengembangan-masyarakat.jpg',
    ],
    'expertise' => [
        'ID' => [
            'Pengembangan Masyarakat',
            'GEDSI (Kesetaraan Gender, Disabilitas & Inklusi)',
            'Riset & Asesmen',
            'Komunikasi & Penceritaan',
            'Konservasi & Lanskap',
            'Kebijakan & Tata Kelola',
            'Iklim & Keberlanjutan',
            'Kemitraan Lintas Sektor',
        ],
        'EN' => [
            'Community Development',
            'GEDSI (Gender & Inclusion)',
            'Research & Assessment',
            'Communication & Storytelling',
            'Conservation & Landscape',
            'Policy & Governance',
            'Climate & Sustainability',
            'Cross-Sector Partnership',
        ],
    ],
    'contributions' => [
        'ID' => [
            ['no' => '01', 'title' => 'Konservasi, Iklim & Keberlanjutan', 'desc' => 'Menghubungkan perlindungan biodiversitas dan ekosistem dengan ketahanan iklim, pengelolaan sumber daya, dan pembangunan berkelanjutan.', 'href' => '/inisiatif?kategori=konservasi', 'tag' => 'Ekosistem & Iklim'],
            ['no' => '02', 'title' => 'Program & Strategi', 'desc' => 'Menerjemahkan kebutuhan dan temuan lapangan menjadi desain, pengembangan, dan penguatan program.', 'href' => '/inisiatif?kategori=program', 'tag' => 'Desain Intervensi'],
            ['no' => '03', 'title' => 'Kemitraan & Kolaborasi', 'desc' => 'Mempertemukan berbagai pihak, keahlian, dan kepentingan untuk membangun kerja bersama lintas sektor.', 'href' => '/kolaborasi', 'tag' => 'Kerja Sama Multi-Pihak'],
            ['no' => '04', 'title' => 'Media, Penceritaan & Kampanye', 'desc' => 'Membawa pengetahuan, pengalaman, dan suara dari lapangan ke ruang publik melalui cerita, media, dan kampanye.', 'href' => '/pengetahuan?kategori=cerita', 'tag' => 'Narasi & Advokasi'],
            ['no' => '05', 'title' => 'Pengembangan Masyarakat', 'desc' => 'Memperkuat kapasitas, partisipasi, kelembagaan, dan inisiatif masyarakat melalui pendekatan yang responsif GEDSI dan kolaboratif.', 'href' => '/inisiatif?kategori=komunitas', 'tag' => 'Pemberdayaan Warga'],
            ['no' => '06', 'title' => 'Riset, Asesmen & Pengetahuan', 'desc' => 'Menghasilkan dan menerjemahkan data, pengalaman, dan pengetahuan untuk memahami persoalan, mendukung keputusan, dan membangun pembelajaran.', 'href' => '/pengetahuan?kategori=riset', 'tag' => 'Kajian Berbasis Bukti'],
        ],
        'EN' => [
            ['no' => '01', 'title' => 'Conservation, Climate & Sustainability', 'desc' => 'Connecting biodiversity and ecosystem protection with climate resilience, resource management, and sustainable development.', 'href' => '/inisiatif?kategori=konservasi', 'tag' => 'Ecosystem & Climate'],
            ['no' => '02', 'title' => 'Program & Strategy', 'desc' => 'Translating field needs and findings into robust program design, development, and contextual scaling.', 'href' => '/inisiatif?kategori=program', 'tag' => 'Intervention Design'],
            ['no' => '03', 'title' => 'Partnership & Collaboration', 'desc' => 'Bringing together diverse stakeholders, expertise, and priorities to forge multi-sector collaborative partnerships.', 'href' => '/kolaborasi', 'tag' => 'Multi-Stakeholder'],
            ['no' => '04', 'title' => 'Media, Storytelling & Campaign', 'desc' => 'Amplifying grassroots knowledge, field experiences, and public voices through compelling stories, media, and campaigns.', 'href' => '/pengetahuan?kategori=cerita', 'tag' => 'Narrative & Advocacy'],
            ['no' => '05', 'title' => 'Community Development', 'desc' => 'Strengthening community capacity, participation, governance, and initiatives through GEDSI-responsive and participatory approaches.', 'href' => '/inisiatif?kategori=komunitas', 'tag' => 'Community Stewardship'],
            ['no' => '06', 'title' => 'Research, Assessment & Knowledge', 'desc' => 'Generating and translating field data, experiences, and evidence-based knowledge to inform decision-making and continuous learning.', 'href' => '/pengetahuan?kategori=riset', 'tag' => 'Evidence-Based Study'],
        ],
    ],
    'hero' => [
        'config' => ['autoplay' => true, 'intervalMs' => 6000, 'transitionEffect' => 'fade', 'pauseOnHover' => true],
        'slides' => [
            [
                'id' => 'slide-1', 'tagline' => 'ANTRABUMI — Organisasi Independen', 'taglineEn' => 'ANTRABUMI — Independent Organization',
                'title' => 'Menghubungkan Pengetahuan, Alam, & Komunitas.', 'titleEn' => 'Connecting Knowledge, Nature, & Communities.',
                'subtitle' => 'Organisasi independen yang bekerja di persimpangan pengetahuan, alam, dan komunitas — menghubungkan riset, pengalaman lapangan, dan kolaborasi untuk perubahan yang bermakna.',
                'subtitleEn' => 'An independent organization working at the intersection of knowledge, nature, and communities — connecting research, field experience, and collaboration for meaningful change.',
                'primaryCtaText' => 'Hubungi Kami', 'primaryCtaTextEn' => 'Contact Us', 'primaryCtaLink' => '/kolaborasi#kontak',
                'secondaryCtaText' => 'Tentang ANTRABUMI', 'secondaryCtaTextEn' => 'About ANTRABUMI', 'secondaryCtaLink' => '/tentang',
                'imageUrl' => '', 'order' => 1, 'isActive' => true,
            ],
            [
                'id' => 'slide-2', 'tagline' => 'Pendekatan Kami — 01 Listen to 05 Learn', 'taglineEn' => 'Our Framework — 01 Listen to 05 Learn',
                'title' => 'Menjembatani Riset & Tindakan Nyata di Lapangan.', 'titleEn' => 'Bridging Research & Real Action in the Field.',
                'subtitle' => 'Setiap kolaborasi dimulai dari memahami konteks, bukan menawarkan solusi instan. Kami mempertemukan bukti ilmiah dengan kearifan komunitas lokal.',
                'subtitleEn' => 'Every collaboration begins with understanding context, not offering instant solutions. We bridge scientific evidence with local community knowledge.',
                'primaryCtaText' => 'Lihat Inisiatif', 'primaryCtaTextEn' => 'View Initiatives', 'primaryCtaLink' => '/inisiatif',
                'secondaryCtaText' => 'Kerangka Kerja', 'secondaryCtaTextEn' => 'Our Framework', 'secondaryCtaLink' => '/tentang#framework',
                'imageUrl' => '', 'order' => 2, 'isActive' => true,
            ],
            [
                'id' => 'slide-3', 'tagline' => 'Pusat Pengetahuan — Knowledge Hub', 'taglineEn' => 'Knowledge Hub — Evidence-Based Learning',
                'title' => 'Mendokumentasikan Pembelajaran untuk Keberlanjutan.', 'titleEn' => 'Documenting Lessons for Long-Term Sustainability.',
                'subtitle' => 'Publikasi, laporan asesmen lapangan, dan artikel mendalam untuk mendukung pengambilan keputusan yang lebih inklusif dan berkelanjutan.',
                'subtitleEn' => 'Publications, field assessments, and in-depth articles supporting more inclusive and sustainable decision-making.',
                'primaryCtaText' => 'Eksplorasi Pengetahuan', 'primaryCtaTextEn' => 'Explore Knowledge', 'primaryCtaLink' => '/pengetahuan',
                'secondaryCtaText' => 'Bermitra dengan Kami', 'secondaryCtaTextEn' => 'Partner with Us', 'secondaryCtaLink' => '/kolaborasi',
                'imageUrl' => '', 'order' => 3, 'isActive' => true,
            ],
        ],
    ],
    'content' => [
        'whyUs' => [
            'badge' => '01 — MENGAPA KAMI HADIR', 'badgeEn' => '01 — WHY WE EXIST',
            'title' => 'Perubahan yang berarti lahir ketika pengetahuan, alam, dan masyarakat saling terhubung.',
            'titleEn' => 'Change becomes meaningful when knowledge, nature, and communities are connected.',
            'leadText' => "Indonesia memiliki kekayaan alam, pengetahuan lokal, dan masyarakat yang terus mencari cara untuk beradaptasi. Namun, berbagai tantangan lingkungan dan pembangunan masih sering ditangani secara terpisah.\n\nPengetahuan tidak selalu menjadi aksi. Pengalaman di lapangan belum selalu menjadi pembelajaran. Dan solusi tidak selalu tumbuh bersama mereka yang akan menjalaninya.",
            'leadTextEn' => "Indonesia possesses rich nature, local knowledge, and communities continuously seeking ways to adapt. However, environmental and developmental challenges are still often addressed in silos.\n\nKnowledge does not always translate into action. Field experiences do not always become learning. And solutions do not always grow with those who will live them.",
            'bridgeTitle' => 'ANTRABUMI Hadir untuk menjembatani ruang tersebut.', 'bridgeTitleEn' => 'ANTRABUMI Exists to Bridge That Space.',
            'bridgeText' => 'Kami menghubungkan riset, pengalaman, pengetahuan lokal, dan kolaborasi untuk memahami persoalan, mengembangkan solusi, dan mendukung perubahan yang relevan bagi manusia dan alam.',
            'bridgeTextEn' => 'We connect research, field experience, local knowledge, and cross-sector collaboration to understand issues holistically, develop contextual solutions, and support meaningful change for people and nature.',
            'imageUrl' => '/images/home/bridge-diagram.svg',
        ],
        'about' => [
            'badge' => '02 — TENTANG ANTRABUMI', 'badgeEn' => '02 — ABOUT ANTRABUMI',
            'title' => 'Menghubungkan pengetahuan menjadi aksi, dan kolaborasi menjadi perubahan.',
            'titleEn' => 'Connecting knowledge into action, and collaboration into change.',
            'description' => 'ANTRABUMI adalah organisasi independen yang bekerja di persimpangan pengetahuan, alam, dan masyarakat. Kami mempertemukan pengalaman lapangan, riset, pengetahuan lokal, dan berbagai perspektif untuk memahami persoalan secara lebih utuh dan mengembangkan pendekatan yang kontekstual.',
            'descriptionEn' => 'ANTRABUMI is an independent organization working at the intersection of knowledge, nature, and communities. We bring together field experience, research, local knowledge, and diverse perspectives to understand challenges holistically and develop contextual approaches.',
            'secondaryText' => 'Kami bekerja bersama komunitas, pemerintah, akademisi, organisasi masyarakat sipil, sektor swasta, dan mitra pembangunan untuk membangun perubahan yang lebih terhubung dan berkelanjutan.',
            'secondaryTextEn' => 'We collaborate with communities, government, academia, civil society, the private sector, and development partners to foster more connected and sustainable change.',
            'diagramUrl' => '/images/home/pillars-diagram.svg',
        ],
        'pillars' => [
            ['id' => '01', 'key' => 'KNOWLEDGE', 'label' => 'Pengetahuan', 'labelEn' => 'Knowledge', 'description' => 'Riset, pembelajaran dari lapangan, dan integrasi pengetahuan lokal untuk melahirkan pendekatan yang kontekstual dan bermakna.', 'descriptionEn' => 'Research, field learning, and integration of local knowledge to produce contextual and meaningful approaches.'],
            ['id' => '02', 'key' => 'NATURE', 'label' => 'Alam', 'labelEn' => 'Nature', 'description' => 'Konservasi, keberlanjutan ekologis, dan mitigasi iklim yang berbasiskan pemahaman ekosistem nyata di lapangan.', 'descriptionEn' => 'Conservation, ecological sustainability, and climate mitigation grounded in real ecosystem understanding from the field.'],
            ['id' => '03', 'key' => 'COMMUNITIES', 'label' => 'Masyarakat / Komunitas', 'labelEn' => 'Communities', 'description' => 'Pengembangan komunitas, inklusi sosial (GEDSI), dan kemitraan kolaboratif lintas sektor yang berpijak pada konteks lokal.', 'descriptionEn' => 'Community development, social inclusion (GEDSI), and collaborative cross-sector partnerships rooted in local context.'],
        ],
        'growth' => [
            'badge' => '03 — BAGAIMANA KAMI BERTUMBUH', 'badgeEn' => '03 — HOW WE GROW',
            'title' => 'Setiap langkah memperluas pengalaman. Setiap pengalaman membentuk cara kami bekerja.',
            'titleEn' => 'Every step expands experience. Every experience shapes how we work.',
            'leadText' => "ANTRABUMI tumbuh dari perjalanan yang dimulai pada tahun 2021. Berbagai pengalaman di lapangan, kolaborasi lintas sektor, dan proses belajar bersama menjadi fondasi yang membentuk identitas organisasi ini.\n\nHari ini, perjalanan tersebut terus berlanjut melalui ANTRABUMI sebagai ruang kolaborasi yang menghubungkan pengetahuan, alam, dan masyarakat untuk menciptakan perubahan yang relevan dan berkelanjutan.",
            'leadTextEn' => "ANTRABUMI grew from a journey that began in 2021. Diverse field experiences, cross-sector collaborations, and mutual learning have become the foundation shaping this organization's identity.",
            'timeline' => [
                ['year' => '2021', 'label' => 'Awal Perjalanan', 'labelEn' => 'The Beginning', 'description' => 'PT Antar Bumi Sahawahita didirikan sebagai awal perjalanan membangun pengalaman dan kolaborasi di bidang lingkungan dan pembangunan berkelanjutan.', 'descriptionEn' => 'PT Antar Bumi Sahawahita was established as the beginning of building field experience and collaboration.'],
                ['year' => '2022', 'label' => 'Belajar dari Lapangan', 'labelEn' => 'Learning from the Field', 'description' => 'Memperluas pengalaman melalui penelitian, pendampingan masyarakat, dan berbagai inisiatif konservasi di lapangan.', 'descriptionEn' => 'Expanding experience through research, community mentoring, and grassroots conservation initiatives.'],
                ['year' => '2023', 'label' => 'Memperluas Kolaborasi', 'labelEn' => 'Expanding Collaboration', 'description' => 'Membangun kolaborasi bersama komunitas, pemerintah, akademisi, sektor swasta, dan organisasi masyarakat sipil.', 'descriptionEn' => 'Forging collaborations with communities, government, academia, private sector, and civil society.'],
                ['year' => '2024', 'label' => 'Memperkuat Pendekatan', 'labelEn' => 'Strengthening Our Approach', 'description' => 'Memperkuat pendekatan yang menghubungkan pengetahuan, konservasi, dan pengembangan masyarakat dalam berbagai program.', 'descriptionEn' => 'Strengthening methodologies that connect knowledge, conservation, and community development across programs.'],
                ['year' => '2025', 'label' => 'Membentuk Identitas', 'labelEn' => 'Forming an Identity', 'description' => 'Menyatukan pengalaman dan jejaring sebagai fondasi lahirnya identitas ANTRABUMI.', 'descriptionEn' => 'Consolidating field experiences and networks as the foundation of the ANTRABUMI identity.'],
                ['year' => '2026', 'label' => 'A New Chapter', 'labelEn' => 'A New Chapter', 'description' => 'ANTRABUMI diperkenalkan sebagai institusi yang menghubungkan pengetahuan, alam, dan masyarakat melalui kolaborasi yang lebih luas.', 'descriptionEn' => 'ANTRABUMI is introduced as an institution connecting knowledge, nature, and communities through wider collaboration.'],
            ],
        ],
        'framework' => [
            'badge' => '04 — CARA KAMI BEKERJA', 'badgeEn' => '04 — HOW WE WORK',
            'title' => 'Setiap kolaborasi dimulai dengan memahami konteks, bukan menawarkan solusi.',
            'titleEn' => 'Every collaboration begins with understanding context, not offering solutions.',
            'leadText' => 'ANTRABUMI menghubungkan berbagai pihak untuk merancang solusi yang relevan dengan kebutuhan di lapangan. Kami percaya bahwa perubahan yang bertahan dibangun melalui proses yang terbuka, kolaboratif, dan terus belajar dari setiap pengalaman.',
            'leadTextEn' => 'ANTRABUMI connects diverse stakeholders to design solutions relevant to on-the-ground needs. We believe enduring change is built through open, collaborative processes.',
            'steps' => [
                ['step' => '01', 'title' => 'DENGARKAN', 'titleEn' => 'LISTEN', 'desc' => 'Memahami konteks dan mendengarkan kebutuhan lapangan sebelum menawarkan solusi.', 'descEn' => 'Understanding context and listening to grassroots needs before offering solutions.'],
                ['step' => '02', 'title' => 'HUBUNGKAN', 'titleEn' => 'CONNECT', 'desc' => 'Menghubungkan perspektif yang beragam, pengetahuan lokal, dan bukti riset ilmiah.', 'descEn' => 'Connecting diverse perspectives, local wisdom, and scientific research evidence.'],
                ['step' => '03', 'title' => 'RANCANG BERSAMA', 'titleEn' => 'CO-CREATE', 'desc' => 'Merancang pendekatan dan solusi bersama komunitas serta pemangku kepentingan terkait.', 'descEn' => 'Designing approaches and solutions collaboratively with communities and stakeholders.'],
                ['step' => '04', 'title' => 'BERTINDAK', 'titleEn' => 'ACT', 'desc' => 'Menjalankan program dan inisiatif nyata secara kontekstual dan bertanggung jawab.', 'descEn' => 'Executing real programs and contextual initiatives responsibly on the ground.'],
                ['step' => '05', 'title' => 'BELAJAR', 'titleEn' => 'LEARN', 'desc' => 'Mendokumentasikan, merefleksikan, dan mengintegrasikan pembelajaran untuk keberlanjutan.', 'descEn' => 'Documenting, reflecting on, and integrating lessons learned for long-term sustainability.'],
            ],
            'gedsiTitle' => 'GEDSI sebagai Pendekatan', 'gedsiTitleEn' => 'GEDSI as an Approach',
            'gedsiText' => 'Gender Equality, Disability and Social Inclusion (GEDSI) menjadi bagian dari cara kami memahami konteks, melibatkan masyarakat, dan merancang solusi. Kami memastikan keberagaman perspektif, pengalaman, akses, dan kebutuhan menjadi bagian dari proses dan pengambilan keputusan.',
            'gedsiTextEn' => 'Gender Equality, Disability and Social Inclusion (GEDSI) is integral to how we understand context, engage communities, and design solutions. We ensure diverse perspectives, accessibility, and needs inform every decision.',
        ],
        'cta' => [
            'badge' => 'KOLABORASI & KEMITRAAN', 'badgeEn' => 'COLLABORATION & PARTNERSHIP',
            'title' => 'Mari Terhubung & Berkolaborasi untuk Perubahan Nyata.', 'titleEn' => "Let's Connect & Collaborate for Meaningful Change.",
            'description' => 'ANTRABUMI membuka ruang kolaborasi lintas sektor bersama komunitas, akademisi, pemerintah, lembaga swadaya, dan mitra pembangunan.',
            'descriptionEn' => 'ANTRABUMI welcomes cross-sector collaboration with communities, academia, government, civil society, and development partners.',
            'primaryButtonText' => 'Mulai Kolaborasi', 'primaryButtonTextEn' => 'Start Collaborating', 'primaryButtonLink' => '/kolaborasi#kontak',
            'secondaryButtonText' => 'Pelajari Lebih Lanjut', 'secondaryButtonTextEn' => 'Learn More', 'secondaryButtonLink' => '/tentang',
        ],
    ],
];