@extends('layouts.app')

@section('title', 'Pengetahuan — ANTRABUMI')
@section('description', 'Arsip pengetahuan ANTRABUMI: riset, laporan, asesmen, artikel, dan wawasan dari lapangan yang dapat diakses publik beserta dokumen PDF unduhan.')
@section('canonical', url('/pengetahuan'))
@section('og_title', 'Pengetahuan — ANTRABUMI')
@section('og_description', 'Riset, laporan, asesmen, artikel, dan wawasan dari lapangan ANTRABUMI.')

@section('content')
@php
    $typeLabels = $isEnglish
        ? ['ALL' => 'All', 'ARTICLE' => 'Article', 'RESEARCH_PUBLICATION' => 'Research & Publication', 'STORY' => 'Field Story']
        : ['ALL' => 'Semua', 'ARTICLE' => 'Artikel', 'RESEARCH_PUBLICATION' => 'Riset & Publikasi', 'STORY' => 'Cerita Lapangan'];
    $subLabels = $isEnglish
        ? ['ALL' => 'All', 'ARTICLE' => 'Articles & Opinions', 'RESEARCH_PUBLICATION' => 'Research & Reports', 'STORY' => 'Field Stories']
        : ['ALL' => 'Semua', 'ARTICLE' => 'Artikel & Opini', 'RESEARCH_PUBLICATION' => 'Riset & Publikasi', 'STORY' => 'Cerita Lapangan'];
    $visibleInitially = $initialType === 'ALL'
        ? count($items)
        : count(array_filter($items, static fn (array $item): bool => $item['type'] === $initialType));
@endphp
<main class="min-h-screen bg-white font-sans text-neutral-900">
    <section class="relative overflow-hidden border-b border-neutral-200/80 bg-gradient-to-b from-[#FBF9F5] via-[#FDFBF7] to-white py-24 sm:py-32">
        <div class="pointer-events-none absolute inset-0 bg-[radial-gradient(#0D5C4D_1px,transparent_1px)] opacity-35 [background-size:32px_32px]"></div>
        <div class="pointer-events-none absolute -right-32 -top-32 h-96 w-96 rounded-full bg-[#0D5C4D]/5 blur-3xl"></div>
        <div class="relative mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10">
            <div class="max-w-4xl space-y-6">
                <div class="inline-flex items-center gap-2 rounded-full border border-[#0D5C4D]/25 bg-white/80 px-4 py-1.5 text-xs font-semibold uppercase tracking-widest text-[#0D5C4D] shadow-sm backdrop-blur-sm"><span class="h-2 w-2 animate-pulse rounded-full bg-[#0D5C4D]"></span>{{ $isEnglish ? 'KNOWLEDGE & RESEARCH' : 'PENGETAHUAN & RISET' }}</div>
                <h1 class="font-heading text-4xl font-extrabold leading-[1.08] tracking-tight text-neutral-950 sm:text-6xl lg:text-[64px]">@if($isEnglish)Knowledge grows when <span class="text-[#0D5C4D]">experience is shared</span>.@else Pengetahuan tumbuh ketika <span class="text-[#0D5C4D]">pengalaman dibagikan</span>.@endif</h1>
                <p class="max-w-2xl text-base font-normal leading-relaxed text-neutral-600 sm:text-xl">{{ $isEnglish ? 'A dedicated hub for field stories, research reports, policy briefs, and contextual learnings from collaborative processes across Indonesia.' : 'Ruang dokumentasi terbuka untuk cerita lapangan, laporan riset, policy brief, dan pembelajaran kontekstual dari proses kerja bersama di berbagai lanskap.' }}</p>
                <nav aria-label="Kategori Pengetahuan" class="flex flex-wrap items-center gap-2.5 pt-4">
                    @foreach(['ALL', 'ARTICLE', 'RESEARCH_PUBLICATION', 'STORY'] as $type)
                        <button type="button" data-knowledge-select="{{ $type }}" class="inline-flex items-center gap-2 rounded-xl px-5 py-2.5 text-xs font-semibold transition-all duration-200 sm:text-sm {{ $initialType === $type ? 'scale-[1.02] bg-[#0D5C4D] text-white shadow-md shadow-[#0D5C4D]/20' : 'border border-neutral-300/80 bg-white text-neutral-700 hover:border-[#0D5C4D]/50 hover:bg-neutral-50' }}"><span>{{ $subLabels[$type] }}</span><span data-knowledge-count="{{ $type }}" class="rounded-full px-2 py-0.5 font-mono text-[10px] {{ $initialType === $type ? 'bg-white/20 text-white' : 'bg-neutral-100 text-neutral-500' }}">{{ $type === 'ALL' ? count($items) : count(array_filter($items, static fn (array $item): bool => $item['type'] === $type)) }}</span></button>
                    @endforeach
                </nav>
            </div>
        </div>
    </section>

    <section class="border-b border-neutral-100 bg-white py-16 sm:py-24">
        <div class="mx-auto grid w-full max-w-[1280px] grid-cols-1 items-start gap-10 px-5 md:px-7 lg:grid-cols-12 lg:gap-14 lg:px-10">
            <article class="group flex flex-col space-y-6 lg:col-span-7">
                <div class="relative aspect-[16/10] w-full overflow-hidden rounded-2xl border border-neutral-200/80 bg-neutral-100 shadow-sm"><img src="{{ $pageImages['field_story'] }}" alt="{{ $isEnglish ? 'Field Story' : 'Cerita Lapangan' }}" class="h-full w-full object-cover transition-transform duration-700 group-hover:scale-105"></div>
                <div class="space-y-3"><p class="font-mono text-xs font-semibold uppercase tracking-wider text-neutral-500">{{ $isEnglish ? 'FIELD STORY · 2026' : 'CERITA LAPANGAN · 2026' }}</p><h2 class="font-heading text-2xl font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D] sm:text-3xl">{{ $isEnglish ? 'Between knowledge, place, and living realities.' : 'Di antara pengetahuan, tempat, dan kehidupan.' }}</h2><p class="text-sm leading-relaxed text-neutral-600 sm:text-base">{{ $isEnglish ? 'Notes from the field on how a challenge reveals itself when we listen more closely.' : 'Catatan dari lapangan tentang bagaimana sebuah persoalan terlihat ketika kita mendengarkan lebih dekat.' }}</p><div class="pt-2"><a href="#arsip" data-knowledge-select="STORY" class="inline-flex items-center gap-2 text-sm font-semibold text-[#0D5C4D] transition-all hover:gap-3 hover:text-[#116958]"><span>{{ $isEnglish ? 'Read stories' : 'Baca cerita' }}</span><span>→</span></a></div></div>
            </article>
            <div class="flex flex-col divide-y divide-neutral-200/90 pt-2 lg:col-span-5 lg:pt-0">
                <article class="group pb-8"><p class="font-mono text-xs font-semibold uppercase tracking-wider text-neutral-400">{{ $isEnglish ? 'OPINION · 2026' : 'OPINI · 2026' }}</p><h3 class="mt-2 font-heading text-lg font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D] sm:text-xl"><a href="#arsip" data-knowledge-select="ARTICLE">{{ $isEnglish ? 'Why context must precede solutions?' : 'Mengapa konteks harus datang sebelum solusi?' }}</a></h3><p class="mt-2 text-xs leading-relaxed text-neutral-600 sm:text-sm">{{ $isEnglish ? 'Reflections on reading development and environmental issues through grassroots realities.' : 'Refleksi tentang cara membaca persoalan pembangunan dan lingkungan.' }}</p></article>
                <article class="group py-8"><p class="font-mono text-xs font-semibold uppercase tracking-wider text-neutral-400">{{ $isEnglish ? 'PUBLICATION · 2026' : 'PUBLIKASI · 2026' }}</p><h3 class="mt-2 font-heading text-lg font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D] sm:text-xl"><a href="#arsip" data-knowledge-select="RESEARCH_PUBLICATION">Research, Assessment &amp; Knowledge</a></h3><p class="mt-2 text-xs leading-relaxed text-neutral-600 sm:text-sm">{{ $isEnglish ? 'A collection of reports and assessments underpinning evidence-based decision making.' : 'Kumpulan laporan dan assessment yang menjadi dasar pengambilan keputusan.' }}</p></article>
                <article class="group pt-8"><p class="font-mono text-xs font-semibold uppercase tracking-wider text-neutral-400">{{ $isEnglish ? 'GUIDE · 2026' : 'PANDUAN · 2026' }}</p><h3 class="mt-2 font-heading text-lg font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D] sm:text-xl"><a href="#arsip" data-knowledge-select="RESEARCH_PUBLICATION">{{ $isEnglish ? 'Learning from collaborative processes' : 'Belajar dari proses kolaborasi' }}</a></h3><p class="mt-2 text-xs leading-relaxed text-neutral-600 sm:text-sm">{{ $isEnglish ? 'Toolkits and learnings ready to be adapted and reused by partner organizations.' : 'Toolkit dan pembelajaran yang dapat digunakan kembali oleh mitra.' }}</p></article>
            </div>
        </div>
    </section>

    <section class="border-b border-neutral-200/80 bg-[#FAF9F5] py-20 sm:py-28">
        <div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><div class="mb-14 space-y-3"><p class="font-mono text-xs font-bold uppercase tracking-[0.25em] text-[#0D5C4D]">{{ $isEnglish ? 'PUBLICATIONS' : 'PUBLIKASI' }}</p><h2 class="font-heading text-3xl font-bold tracking-tight text-neutral-950 sm:text-4xl">{{ $isEnglish ? 'Documents to read, use, and share.' : 'Dokumen yang dapat dibaca, digunakan, dan dibagikan.' }}</h2><p class="max-w-3xl text-sm leading-relaxed text-neutral-600 sm:text-base">{{ $isEnglish ? 'Open knowledge resources produced through rigorous field research, stakeholder dialogues, and participatory community development.' : 'Sumber daya pengetahuan terbuka yang dihasilkan melalui kajian lapangan berdisiplin, dialog multi-pihak, serta pendampingan masyarakat berbasis bukti.' }}</p></div>
            <div class="grid grid-cols-1 gap-8 md:grid-cols-3">
                @php
                    $publicationCards = [
                    ['key' => 'assessment', 'image' => $pageImages['assessment'], 'altId' => 'Laporan dan Asesmen', 'altEn' => 'Reports and Assessments', 'tagId' => 'LAPORAN', 'tagEn' => 'REPORT', 'accent' => 'text-[#0D5C4D]', 'title' => 'Assessment & programme learning', 'descId' => 'Dokumen hasil riset dan proses pembelajaran.', 'descEn' => 'Research reports and continuous learning processes.', 'bodyId' => 'Dokumentasi komprehensif yang memuat kajian baseline ekologi, pemetaan bentang alam pesisir dan darat, serta evaluasi program berbasis data lapangan yang terverifikasi. Disusun secara multi-disiplin untuk memberikan gambaran faktual tentang kondisi bentang alam, dinamika sosial ekonomi komunitas, dan rekomendasi intervensi berkelanjutan.', 'bodyEn' => 'Comprehensive reports documenting ecological baselines, marine and terrestrial landscape mapping, and multi-stakeholder program evaluations. Synthesizes scientific methods with empirical field data to provide actionable evidence for long-term sustainability interventions.', 'tagsId' => ['Baseline Ekologi', 'Pemetaan Spasial', 'Evaluasi Program'], 'tagsEn' => ['Ecological Baseline', 'Spatial Mapping', 'Program Review']],
                    ['key' => 'policy_brief', 'image' => $pageImages['policy_brief'], 'altId' => 'Policy Brief', 'altEn' => 'Policy Brief', 'tagId' => 'POLICY BRIEF', 'tagEn' => 'POLICY BRIEF', 'accent' => 'text-[#2B8282]', 'title' => 'Knowledge for better decisions', 'descId' => 'Ringkasan pengetahuan untuk ruang kebijakan dan kolaborasi.', 'descEn' => 'Knowledge synthesis for policy spaces and collaborative governance.', 'bodyId' => 'Ringkasan strategis yang menerjemahkan data riset kompleks menjadi poin-poin implikasi kebijakan yang ringkas dan lugas. Ditujukan bagi pembuat kebijakan, instansi pemerintah, dan mitra pembangunan untuk merumuskan tata kelola bentang alam yang adil, inklusif, dan adaptif terhadap perubahan iklim.', 'bodyEn' => 'Concise, strategic briefs translating complex technical research into clear, practical policy insights. Designed specifically for regional policymakers, ministries, and civil society leaders to shape responsive regulations, equitable resource distribution, and climate-resilient governance.', 'tagsId' => ['Ringkasan Eksekutif', 'Rekomendasi Kebijakan', 'Tata Kelola Wilayah'], 'tagsEn' => ['Executive Brief', 'Policy Recommendations', 'Landscape Governance']],
                    ['key' => 'toolkit', 'image' => $pageImages['toolkit'], 'altId' => 'Toolkit & Panduan', 'altEn' => 'Toolkit & Field Guides', 'tagId' => 'TOOLKIT', 'tagEn' => 'TOOLKIT', 'accent' => 'text-[#D96B27]', 'title' => 'Community-centred approaches', 'descId' => 'Panduan praktis dari pengalaman lapangan.', 'descEn' => 'Actionable toolkits and operational guides grounded in field experience.', 'bodyId' => 'Panduan kerja langkah-demi-langkah dan instrumen partisipatif siap pakai yang diuji langsung bersama masyarakat. Menyediakan instrumen asesmen GEDSI (kesetaraan gender, disabilitas, dan inklusi sosial), lembar kerja fasilitasi desa, metode pemetaan partisipatif, serta protokol monitoring mandiri warga.', 'bodyEn' => 'Ready-to-deploy participatory toolkits, facilitation guides, and practical instruments tested alongside local communities. Includes GEDSI assessment matrices (Gender Equality, Disability, and Social Inclusion), village facilitation modules, and citizen self-monitoring protocols.', 'tagsId' => ['Kerangka GEDSI', 'Modul Fasilitasi FGD', 'Monitoring Warga'], 'tagsEn' => ['GEDSI Framework', 'FGD Modules', 'Citizen Monitoring']],
                    ];
                @endphp
                @foreach($publicationCards as $card)
                    <article class="group flex flex-col justify-between overflow-hidden rounded-2xl border border-neutral-200/90 bg-white shadow-sm transition-all hover:-translate-y-1 hover:border-[#0D5C4D]/50 hover:shadow-xl"><div><div class="relative aspect-[16/10] w-full overflow-hidden bg-neutral-100"><img src="{{ $card['image'] }}" alt="{{ $isEnglish ? $card['altEn'] : $card['altId'] }}" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105"><span class="absolute left-3 top-3 rounded-md bg-white/90 px-2.5 py-1 font-mono text-[10px] font-bold uppercase tracking-wider shadow-sm backdrop-blur-sm {{ $card['accent'] }}">{{ $isEnglish ? $card['tagEn'] : $card['tagId'] }}</span></div><div class="space-y-3 p-6 sm:p-7"><h3 class="font-heading text-xl font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D]">{{ $card['title'] }}</h3><p class="text-xs font-medium text-neutral-700">{{ $isEnglish ? $card['descEn'] : $card['descId'] }}</p><div class="space-y-2 border-t border-neutral-100 pt-2 text-xs leading-relaxed text-neutral-600"><p>{{ $isEnglish ? $card['bodyEn'] : $card['bodyId'] }}</p><div class="flex flex-wrap gap-1.5 pt-1">@foreach($isEnglish ? $card['tagsEn'] : $card['tagsId'] as $tag)<span class="rounded bg-neutral-100 px-2 py-0.5 font-mono text-[10px] text-neutral-600">{{ $tag }}</span>@endforeach</div></div></div></div><div class="mt-4 border-t border-neutral-100/60 p-6 pt-4 sm:p-7 sm:pt-4"><a href="#arsip" data-knowledge-select="RESEARCH_PUBLICATION" class="inline-flex items-center gap-1.5 text-xs font-semibold text-[#0D5C4D] hover:underline"><span>{{ $isEnglish ? 'Explore' : 'Telusuri' }} {{ $isEnglish ? $card['tagEn'] : $card['tagId'] }}</span><span>→</span></a></div></article>
                @endforeach
            </div>
        </div>
    </section>

    <section id="arsip" data-knowledge-archive data-initial-type="{{ $initialType }}" class="bg-white py-20 sm:py-28">
        <div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10">
            <div class="mb-10 flex flex-col gap-6 border-b border-neutral-200 pb-6 md:flex-row md:items-end md:justify-between"><div><p class="font-mono text-xs font-semibold uppercase tracking-wider text-[#0D5C4D]">{{ $isEnglish ? 'EXPLORE ARCHIVE' : 'TELUSURI ARSIP' }}</p><h2 class="mt-2 font-heading text-2xl font-bold text-neutral-950 sm:text-3xl">{{ $isEnglish ? 'All Publications & Insights' : 'Semua Publikasi & Tulisan Lapangan' }}</h2><p class="mt-1 text-sm text-neutral-500">{{ $isEnglish ? 'Browse publications, research briefs, and articles produced by the ANTRABUMI team.' : 'Telusuri publikasi resmi, catatan refleksi, dan riset yang diterbitkan oleh tim ANTRABUMI.' }}</p></div><label class="relative w-full shrink-0 md:w-72"><span class="sr-only">{{ $isEnglish ? 'Search by title or topic' : 'Cari judul atau topik' }}</span><input type="search" data-knowledge-search placeholder="{{ $isEnglish ? 'Search by title or topic...' : 'Cari judul atau topik...' }}" class="w-full rounded-xl border border-neutral-300 bg-neutral-50 py-2.5 pl-10 pr-10 text-xs text-neutral-900 placeholder:text-neutral-400 focus:border-[#0D5C4D] focus:bg-white focus:outline-none focus:ring-2 focus:ring-[#0D5C4D]/10"><svg class="absolute left-3.5 top-3 h-4 w-4 text-neutral-400" fill="none" viewBox="0 0 24 24" stroke="currentColor" aria-hidden="true"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" /></svg><button type="button" data-knowledge-clear hidden aria-label="{{ $isEnglish ? 'Clear search' : 'Hapus pencarian' }}" class="absolute right-3.5 top-2.5 text-xs text-neutral-400 hover:text-neutral-600">✕</button></label></div>
            <div class="mb-10 flex items-center gap-2 overflow-x-auto pb-2">
                @foreach(['ALL', 'ARTICLE', 'RESEARCH_PUBLICATION', 'STORY'] as $type)
                    <button type="button" data-knowledge-filter="{{ $type }}" aria-pressed="{{ $initialType === $type ? 'true' : 'false' }}" class="shrink-0 rounded-full px-4 py-1.5 text-xs font-medium transition-all {{ $initialType === $type ? 'bg-[#0D5C4D] font-semibold text-white shadow-sm' : 'bg-neutral-100 text-neutral-600 hover:bg-neutral-200' }}">{{ $typeLabels[$type] }}</button>
                @endforeach
            </div>
            <div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
                @foreach($items as $item)
                    @php
                        $initiallyVisible = $initialType === 'ALL' || $initialType === $item['type'];
                        $typeLabel = $typeLabels[$item['type']] ?? $item['type'];
                        $itemDate = $item['publishedAt'] ? \Illuminate\Support\Carbon::parse($item['publishedAt'])->locale($isEnglish ? 'en' : 'id')->isoFormat('LL') : null;
                    @endphp
                    <article data-knowledge-card data-type="{{ $item['type'] }}" data-title="{{ $item['title'] }}" data-excerpt="{{ $item['excerpt'] }}" @if(!$initiallyVisible) hidden @endif class="group relative flex flex-col overflow-hidden rounded-2xl border border-neutral-200/80 bg-white transition-all duration-300 hover:-translate-y-1 hover:border-[#0D5C4D]/50 hover:shadow-xl">
                        @if($item['featured'])<span class="absolute right-3 top-3 z-10 rounded-full bg-[#E5A823] px-2.5 py-0.5 font-mono text-[10px] font-bold text-neutral-950 shadow-md">★ {{ $isEnglish ? 'Featured' : 'Unggulan' }}</span>@endif
                        <a href="/pengetahuan/{{ $item['slug'] }}" class="relative block aspect-video w-full overflow-hidden bg-neutral-100">
                            @if($item['coverMedia']['url'] ?? null)<img src="{{ $item['coverMedia']['url'] }}" alt="{{ $item['coverMedia']['altText'] ?: $item['title'] }}" loading="lazy" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105">@else<div class="relative flex h-full w-full flex-col justify-between overflow-hidden bg-gradient-to-br from-[#0B1E1A] via-[#116958] to-[#0D5C4D] p-5 text-white"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(#E5A823_1px,transparent_1px)] opacity-15 [background-size:16px_16px]"></div><div class="relative z-10 flex items-center justify-between"><span class="inline-flex items-center rounded-full border border-[#E5A823]/40 bg-[#E5A823]/25 px-2.5 py-0.5 font-mono text-[11px] font-semibold text-[#E5A823]">{{ $typeLabel }}</span><span class="font-mono text-[11px] uppercase text-white/60">ANTRABUMI</span></div><p class="relative z-10 line-clamp-2 pt-4 font-heading text-sm font-bold leading-snug">{{ $item['title'] }}</p></div>@endif
                        </a>
                        <div class="flex flex-1 flex-col justify-between gap-4 p-6"><div class="space-y-2.5"><div class="flex flex-wrap items-center justify-between gap-2"><span class="rounded-md bg-[#0D5C4D]/10 px-2 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wider text-[#0D5C4D]">{{ $typeLabel }}</span><div class="flex items-center gap-1.5 font-mono text-xs text-neutral-400">@if($itemDate)<time datetime="{{ \Illuminate\Support\Carbon::parse($item['publishedAt'])->toIso8601String() }}">{{ $itemDate }}</time>@endif @if($item['authorName'])<span title="{{ $item['authorName'] }}" class="max-w-[130px] truncate">· {{ $item['authorName'] }}</span>@endif</div></div><h3 class="line-clamp-2 font-heading text-base font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D]"><a href="/pengetahuan/{{ $item['slug'] }}" class="hover:underline">{{ $item['title'] }}</a></h3>@if($item['excerpt'])<p class="line-clamp-2 text-xs leading-relaxed text-neutral-600">{{ $item['excerpt'] }}</p>@endif</div>
                            @if(count($item['downloads']) > 0)<div class="space-y-2 rounded-xl border border-neutral-200/90 bg-neutral-50/80 p-2.5"><div class="flex min-w-0 items-center gap-1.5 text-xs"><span class="flex h-5 w-5 shrink-0 items-center justify-center rounded bg-red-100 font-mono text-[9px] font-bold text-red-600">PDF</span><span class="truncate text-[11px] font-medium text-neutral-700">{{ $item['downloads'][0]['label'] ?: ($isEnglish ? 'Research Brief' : 'Dokumen Riset') }}</span></div><div class="flex items-center gap-2 border-t border-neutral-200/60 pt-1"><button type="button" data-pdf-open data-pdf-url="{{ $item['downloads'][0]['url'] }}" data-pdf-title="{{ $item['downloads'][0]['label'] ?: $item['title'] }}" data-pdf-category="{{ $typeLabel }}" class="inline-flex min-h-8 flex-1 items-center justify-center gap-1 rounded-lg border border-neutral-200 bg-white py-1 text-[11px] font-semibold text-neutral-700 hover:border-[#0D5C4D] hover:text-[#0D5C4D]">👁 {{ $isEnglish ? 'View PDF' : 'Lihat PDF' }}</button><a href="{{ $item['downloads'][0]['url'] }}" download class="inline-flex min-h-8 flex-1 items-center justify-center gap-1 rounded-lg bg-[#0D5C4D] py-1 text-[11px] font-semibold text-white shadow-sm hover:bg-[#116958]">↓ {{ $isEnglish ? 'Download' : 'Unduh' }}</a></div></div>@endif
                            <a href="/pengetahuan/{{ $item['slug'] }}" class="flex items-center justify-between border-t border-neutral-100 pt-3 text-xs font-semibold text-[#0D5C4D] group-hover:text-[#116958]"><span>{{ $isEnglish ? 'Read article' : 'Baca selengkapnya' }}</span><span>→</span></a>
                        </div>
                    </article>
                @endforeach
            </div>
            <div data-knowledge-empty @if($visibleInitially > 0) hidden @endif class="mt-6 flex min-h-[220px] flex-col items-center justify-center rounded-2xl border border-dashed border-neutral-200 bg-neutral-50/50 p-8 text-center"><p class="text-sm font-medium text-neutral-600">{{ $isEnglish ? 'No publication matches your search / category filter.' : 'Belum ada dokumen publikasi yang cocok dengan filter atau kata kunci ini.' }}</p><button type="button" data-knowledge-reset class="mt-3 text-xs font-semibold text-[#0D5C4D] underline hover:text-[#116958]">{{ $isEnglish ? 'Reset all filters' : 'Reset semua filter' }}</button></div>
        </div>
    </section>

    <section class="border-t border-neutral-100 bg-[#FBF9F4] py-16 sm:py-20"><div class="mx-auto w-full max-w-[760px] px-5 md:px-7 lg:px-10"><div class="space-y-5 text-center"><span class="inline-flex items-center rounded-full bg-[#0D5C4D]/10 px-3.5 py-1 font-mono text-xs font-semibold text-[#0D5C4D]">{{ $isEnglish ? 'Knowledge Collaboration' : 'Kolaborasi Pengetahuan' }}</span><h2 class="font-heading text-2xl font-bold text-neutral-950 sm:text-3xl">{{ $isEnglish ? 'Want to co-create research or publish with ANTRABUMI?' : 'Ingin meriset bersama atau menerbitkan kajian bersama ANTRABUMI?' }}</h2><p class="text-sm leading-relaxed text-neutral-600">{{ $isEnglish ? 'We partner with universities, independent researchers, non-profits, and policy makers to produce evidence-based studies and contextual analyses.' : 'Kami bermitra dengan perguruan tinggi, peneliti independen, organisasi masyarakat sipil, dan pengambil kebijakan untuk menghasilkan kajian berbasis bukti yang kontekstual dan aplikatif.' }}</p><a href="/kolaborasi" class="inline-flex h-12 items-center rounded-xl bg-gradient-to-r from-[#0D5C4D] via-[#116958] to-[#147A66] px-8 text-sm font-semibold text-white shadow-md shadow-[#0D5C4D]/25 transition hover:-translate-y-0.5 hover:shadow-lg">{{ $isEnglish ? 'Start Knowledge Partnership' : 'Mulai Kemitraan Riset' }}</a></div></div></section>
</main>

<dialog data-pdf-modal class="m-auto h-[92vh] max-h-[900px] w-[min(96vw,64rem)] max-w-none overflow-hidden rounded-2xl border border-neutral-200 bg-white p-0 shadow-2xl backdrop:bg-black/75">
    <div class="flex h-full flex-col"><div class="flex items-center justify-between border-b border-neutral-200 bg-neutral-50/90 px-4 py-3.5 sm:px-6"><div class="flex min-w-0 items-center gap-3 pr-4"><span class="flex h-8 w-8 shrink-0 items-center justify-center rounded-lg border border-red-500/20 bg-red-500/10 text-xs font-bold text-red-600">PDF</span><div class="min-w-0"><div class="flex items-center gap-2"><h2 data-pdf-modal-title class="truncate font-heading text-sm font-bold text-neutral-900 sm:text-base"></h2><span data-pdf-modal-category class="hidden rounded-md bg-[#0D5C4D]/10 px-2 py-0.5 font-mono text-[10px] font-semibold text-[#0D5C4D] sm:inline-block"></span></div><p class="text-[11px] text-neutral-500">{{ $isEnglish ? 'Document Reader & Preview' : 'Pratinjau Dokumen ANTRABUMI' }}</p></div></div><div class="flex shrink-0 items-center gap-2"><a data-pdf-modal-open href="#" target="_blank" rel="noopener noreferrer" class="hidden items-center rounded-lg border border-neutral-200 bg-white px-3 py-1.5 text-xs font-semibold text-neutral-700 hover:bg-neutral-50 sm:inline-flex">{{ $isEnglish ? 'Full Tab' : 'Tab Baru' }}</a><a data-pdf-modal-download href="#" download class="inline-flex items-center rounded-lg bg-[#0D5C4D] px-3.5 py-1.5 text-xs font-semibold text-white hover:bg-[#116958]">{{ $isEnglish ? 'Download PDF' : 'Unduh PDF' }}</a><button type="button" data-pdf-modal-close aria-label="{{ $isEnglish ? 'Close' : 'Tutup' }}" class="flex h-8 w-8 items-center justify-center rounded-lg text-neutral-500 hover:bg-neutral-200/70 hover:text-neutral-900">×</button></div></div><div class="relative min-h-0 flex-1 bg-neutral-100"><iframe data-pdf-modal-frame title="PDF preview" class="h-full w-full border-0"></iframe><div class="absolute bottom-3 left-1/2 flex -translate-x-1/2 items-center gap-2 rounded-full border border-neutral-200/90 bg-white/90 px-4 py-1.5 text-[11px] text-neutral-600 shadow-lg backdrop-blur-sm"><span>{{ $isEnglish ? 'Trouble viewing preview?' : 'Kendala menampilkan preview?' }}</span><a data-pdf-modal-direct href="#" target="_blank" rel="noopener noreferrer" class="font-bold text-[#0D5C4D] hover:underline">{{ $isEnglish ? 'Open directly →' : 'Buka langsung →' }}</a></div></div></div>
</dialog>
@endsection