@extends('layouts.app')

@section('title', 'Pengalaman — ANTRABUMI')
@section('description', 'Kumpulan pengalaman lapangan ANTRABUMI di berbagai konteks — menghubungkan riset, asesmen, dan aksi di tingkat komunitas untuk melahirkan pendekatan yang berakar kuat pada realitas.')
@section('canonical', url('/pengalaman'))
@section('og_title', 'Pengalaman — ANTRABUMI')
@section('og_description', 'Pengalaman dan inisiatif ANTRABUMI: asesmen, pelatihan, pengembangan program, dan kolaborasi lapangan.')

@section('content')
@php
    $categoryColors = [
        'Konservasi & Lanskap' => ['text' => '#0D5C4D', 'bg' => '#0D5C4D12'],
        'Kelautan & Pesisir' => ['text' => '#2B8282', 'bg' => '#2B828212'],
        'Community Development' => ['text' => '#D96B27', 'bg' => '#D96B2712'],
        'Research & Assessment' => ['text' => '#116958', 'bg' => '#11695812'],
        'Conservation, Climate & Sustainability' => ['text' => '#0D5C4D', 'bg' => '#0D5C4D12'],
    ];
    $years = collect($experiences)->pluck('year')->unique()->sortDesc()->values();
    $categories = collect($experiences)->pluck('category')->filter()->unique()->values();
    $featured = collect($experiences)->where('featured', true)->take(2);
@endphp
<main class="min-h-screen bg-white">
    <section class="relative overflow-hidden border-b border-neutral-100 bg-[#0B1E1A] py-20 text-white lg:py-28"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(#0D5C4D_1px,transparent_1px)] opacity-10 [background-size:24px_24px]"></div><div class="pointer-events-none absolute -right-40 -top-40 h-96 w-96 rounded-full bg-[#0D5C4D]/25 blur-3xl"></div><div class="pointer-events-none absolute -bottom-40 -left-40 h-96 w-96 rounded-full bg-[#D96B27]/15 blur-3xl"></div><div class="relative z-10 mx-auto w-full max-w-[1280px] space-y-6 px-5 md:px-7 lg:px-10"><div class="inline-flex items-center gap-2 rounded-full border border-[#0D5C4D]/60 bg-[#0D5C4D]/30 px-3.5 py-1 backdrop-blur-sm"><span class="h-1.5 w-1.5 rounded-full bg-[#E5A823]"></span><span class="font-mono text-xs font-semibold uppercase tracking-wider text-white/90">{{ $isEnglish ? 'Field Experiences' : 'Pengalaman Lapangan' }}</span></div><h1 class="max-w-3xl font-heading text-3xl font-bold leading-tight tracking-tight text-white sm:text-5xl">{{ $isEnglish ? 'Experiences that shape the way we work.' : 'Pengalaman yang membentuk cara kami bekerja.' }}</h1><p class="max-w-3xl text-base leading-relaxed text-neutral-300 sm:text-lg">{{ $isEnglish ? "ANTRABUMI's collective engagements — connecting research, assessment, and community action to develop grounded, contextual approaches." : 'Kumpulan pengalaman ANTRABUMI di berbagai konteks — menghubungkan riset, asesmen, dan aksi komunitas untuk pendekatan yang berakar pada realitas lapangan.' }}</p><div class="flex flex-wrap items-center gap-6 pt-2 font-mono text-xs text-neutral-400"><div class="flex items-center gap-2"><span class="font-semibold text-white">{{ count($experiences) }}</span><span>{{ $isEnglish ? 'Documented Experiences' : 'Pengalaman Terdokumentasi' }}</span></div><span class="hidden text-neutral-600 sm:inline">·</span><div class="flex items-center gap-2"><span class="font-semibold text-white">2021 — 2026</span><span>{{ $isEnglish ? 'Timeline Scope' : 'Rentang Waktu' }}</span></div></div></div></section>

    @if($featured->isNotEmpty())
        <section class="border-b border-neutral-100 bg-[#F5FAF8] py-12 lg:py-16"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><p class="mb-6 font-mono text-xs font-bold uppercase tracking-widest text-[#0D5C4D]">{{ $isEnglish ? 'Featured Experience' : 'Pengalaman Unggulan' }}</p><div class="grid grid-cols-1 gap-6 lg:grid-cols-2">
            @foreach($featured as $experience)
                @php($style = $categoryColors[$experience['category'] ?? ''] ?? ['text' => '#0D5C4D', 'bg' => '#0D5C4D12'])
                <a href="/pengalaman/{{ $experience['slug'] }}" class="group flex flex-col overflow-hidden rounded-2xl border border-[#0D5C4D]/20 bg-white shadow-sm transition-all hover:-translate-y-1 hover:shadow-lg"><div class="relative aspect-video w-full overflow-hidden bg-neutral-100">@if($experience['coverMedia']['url'] ?? null)<img src="{{ $experience['coverMedia']['url'] }}" alt="{{ $experience['coverMedia']['altText'] ?: $experience['title'] }}" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105">@else<div class="relative flex h-full w-full flex-col justify-between overflow-hidden bg-gradient-to-br from-[#0B1E1A] via-[#0D5C4D] to-[#116958] p-6 text-white"><div class="absolute inset-0 bg-[radial-gradient(#E5A823_1px,transparent_1px)] opacity-15 [background-size:16px_16px]"></div><div class="relative z-10 flex items-center justify-between"><span class="rounded-full border border-[#E5A823]/40 bg-[#E5A823]/25 px-2.5 py-0.5 font-mono text-[11px] font-semibold text-[#E5A823]">{{ $experience['year'] }}</span><span class="font-mono text-[11px] uppercase tracking-wider text-white/60">ANTRABUMI</span></div><p class="relative z-10 line-clamp-2 font-heading text-lg font-bold leading-snug">{{ $experience['title'] }}</p></div>@endif</div><div class="flex flex-1 flex-col gap-3 p-6"><div class="flex flex-wrap items-center gap-2">@if($experience['category'])<span style="color:{{ $style['text'] }};background:{{ $style['bg'] }}" class="rounded-md px-2.5 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wide">{{ $experience['category'] }}</span>@endif<span class="font-mono text-[10px] text-neutral-400">{{ $experience['year'] }}</span></div><h2 class="font-heading text-lg font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D]">{{ $experience['title'] }}</h2>@if($experience['excerpt'])<p class="line-clamp-2 text-sm leading-relaxed text-neutral-600">{{ $experience['excerpt'] }}</p>@endif @if($experience['location'] || $experience['clientName'])<div class="flex flex-wrap gap-3 font-mono text-[11px] text-neutral-400">@if($experience['location'])<span>📍 {{ $experience['location'] }}</span>@endif @if($experience['clientName'])<span>🤝 {{ $experience['clientName'] }}</span>@endif</div>@endif<div class="mt-auto flex items-center justify-between border-t border-neutral-100 pt-3 text-xs font-semibold text-[#0D5C4D]"><span>{{ $isEnglish ? 'View experience' : 'Lihat pengalaman' }}</span><span>→</span></div></div></a>
            @endforeach
        </div></div></section>
    @endif

    <section class="sticky top-20 z-20 border-b border-neutral-200/80 bg-white/95 py-4 shadow-sm backdrop-blur-md"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div class="flex flex-wrap items-center gap-2"><span class="mr-1 shrink-0 font-mono text-xs font-medium text-neutral-400">{{ $isEnglish ? 'Year:' : 'Tahun:' }}</span><button type="button" data-exp-year="ALL" class="rounded-full bg-[#0D5C4D] px-3 py-1 text-xs font-medium text-white shadow-sm">{{ $isEnglish ? 'All' : 'Semua' }}</button>@foreach($years as $year)<button type="button" data-exp-year="{{ $year }}" class="rounded-full bg-neutral-100 px-3 py-1 text-xs font-medium text-neutral-600 transition hover:bg-neutral-200">{{ $year }}</button>@endforeach @if($categories->isNotEmpty())<label class="ml-2 hidden shrink-0 font-mono text-xs font-medium text-neutral-400 sm:inline">{{ $isEnglish ? 'Category:' : 'Kategori:' }}</label><select data-exp-category class="rounded-full border border-neutral-200 bg-neutral-50 px-3 py-1 text-xs text-neutral-600 focus:border-[#0D5C4D] focus:outline-none"><option value="ALL">{{ $isEnglish ? 'All Categories' : 'Semua Kategori' }}</option>@foreach($categories as $category)<option value="{{ $category }}">{{ $category }}</option>@endforeach</select>@endif</div><label class="relative w-full shrink-0 sm:w-60"><span class="sr-only">{{ $isEnglish ? 'Search experiences' : 'Cari pengalaman' }}</span><input data-exp-search type="search" placeholder="{{ $isEnglish ? 'Search experiences...' : 'Cari pengalaman...' }}" class="w-full rounded-xl border border-neutral-200 bg-neutral-50 py-1.5 pl-9 pr-8 text-xs text-neutral-900 placeholder:text-neutral-400 focus:border-[#0D5C4D] focus:bg-white focus:outline-none focus:ring-1 focus:ring-[#0D5C4D]"><button data-exp-clear type="button" hidden aria-label="Hapus pencarian" class="absolute right-3 top-2 text-xs text-neutral-400 hover:text-neutral-600">✕</button></label></div></div></section>

    <section data-experience-archive class="bg-white py-12 lg:py-16"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><p data-exp-count class="mb-6 font-mono text-xs text-neutral-400">{{ $isEnglish ? 'Showing '.count($experiences).' experience'.(count($experiences) !== 1 ? 's' : '') : 'Menampilkan '.count($experiences).' pengalaman' }}</p><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
        @foreach($experiences as $experience)
            @php($style = $categoryColors[$experience['category'] ?? ''] ?? ['text' => '#0D5C4D', 'bg' => '#0D5C4D12'])
            <a data-experience-card data-year="{{ $experience['year'] }}" data-category="{{ $experience['category'] }}" data-search="{{ $experience['title'].' '.$experience['excerpt'].' '.$experience['location'].' '.$experience['category'] }}" href="/pengalaman/{{ $experience['slug'] }}" class="group flex flex-col overflow-hidden rounded-2xl border border-neutral-200/90 bg-white transition-all duration-300 hover:-translate-y-1 hover:border-[#0D5C4D]/60 hover:shadow-xl"><div class="relative aspect-video w-full overflow-hidden bg-neutral-100">@if($experience['coverMedia']['url'] ?? null)<img src="{{ $experience['coverMedia']['url'] }}" alt="{{ $experience['coverMedia']['altText'] ?: $experience['title'] }}" loading="lazy" class="h-full w-full object-cover transition-transform duration-500 group-hover:scale-105">@else<div class="relative flex h-full w-full flex-col justify-between overflow-hidden bg-gradient-to-br from-[#0B1E1A] via-[#0D5C4D] to-[#116958] p-5 text-white"><div class="absolute inset-0 bg-[radial-gradient(#E5A823_1px,transparent_1px)] opacity-15 [background-size:16px_16px]"></div><div class="relative z-10 flex items-center justify-between"><span class="rounded-full border border-[#E5A823]/40 bg-[#E5A823]/25 px-2.5 py-0.5 font-mono text-[11px] font-semibold text-[#E5A823]">{{ $experience['year'] }}</span><span class="font-mono text-[11px] uppercase tracking-wider text-white/60">ANTRABUMI</span></div><p class="relative z-10 line-clamp-2 pt-4 font-heading text-sm font-bold leading-snug">{{ $experience['title'] }}</p></div>@endif</div><div class="flex flex-1 flex-col justify-between gap-3 p-5"><div class="space-y-2"><div class="flex flex-wrap items-center gap-2">@if($experience['category'])<span style="color:{{ $style['text'] }};background:{{ $style['bg'] }}" class="rounded-md px-2.5 py-0.5 font-mono text-[10px] font-bold uppercase tracking-wide">{{ $experience['category'] }}</span>@endif<span class="font-mono text-[10px] text-neutral-400">{{ $experience['year'] }}</span></div><h2 class="font-heading text-base font-bold leading-snug text-neutral-950 transition-colors group-hover:text-[#0D5C4D]">{{ $experience['title'] }}</h2>@if($experience['excerpt'])<p class="line-clamp-2 text-xs leading-relaxed text-neutral-600">{{ $experience['excerpt'] }}</p>@endif</div>@if($experience['location'] || $experience['clientName'])<div class="flex flex-wrap gap-3 font-mono text-[10px] text-neutral-400">@if($experience['location'])<span>📍 {{ $experience['location'] }}</span>@endif @if($experience['clientName'])<span>🤝 {{ $experience['clientName'] }}</span>@endif</div>@endif<div class="flex items-center justify-between border-t border-neutral-100 pt-3 text-xs font-semibold text-[#0D5C4D]"><span>{{ $isEnglish ? 'View experience' : 'Lihat pengalaman' }}</span><span>→</span></div></div></a>
        @endforeach
        </div><div data-exp-empty hidden class="flex min-h-[260px] flex-col items-center justify-center rounded-2xl border border-dashed border-neutral-200 bg-neutral-50 p-10 text-center"><p class="text-sm font-medium text-neutral-600">{{ $isEnglish ? 'No experiences match your filter.' : 'Tidak ada pengalaman yang cocok dengan filter.' }}</p><button data-exp-reset type="button" class="mt-3 text-xs font-semibold text-[#0D5C4D] underline hover:text-[#116958]">{{ $isEnglish ? 'Reset filters' : 'Reset filter' }}</button></div></div></section>

    <section class="border-t border-neutral-100 bg-neutral-50 py-16 lg:py-20"><div class="mx-auto w-full max-w-[760px] space-y-5 px-5 text-center md:px-7 lg:px-10"><span class="inline-flex items-center rounded-full bg-[#0D5C4D]/10 px-3 py-1 font-mono text-xs font-semibold text-[#0D5C4D]">{{ $isEnglish ? 'Work Together' : 'Bekerja Bersama' }}</span><h2 class="font-heading text-2xl font-bold text-neutral-950 sm:text-3xl">{{ $isEnglish ? 'Interested in building an experience together?' : 'Ingin membangun pengalaman bersama?' }}</h2><p class="text-sm leading-relaxed text-neutral-600">{{ $isEnglish ? 'ANTRABUMI works with organizations, governments, academics, and communities to co-create grounded, contextual programs.' : 'ANTRABUMI bekerja bersama organisasi, pemerintah, akademisi, dan komunitas untuk merancang program yang kontekstual dan berdampak.' }}</p><a href="/kolaborasi#kontak" class="inline-flex h-12 items-center rounded-xl bg-gradient-to-r from-[#0D5C4D] via-[#116958] to-[#147A66] px-8 text-sm font-semibold text-white shadow-md shadow-[#0D5C4D]/25 transition-all hover:-translate-y-0.5 hover:shadow-lg">{{ $isEnglish ? 'Discuss a Collaboration' : 'Diskusikan Kolaborasi' }}</a></div></section>
</main>
@endsection