@extends('layouts.app')

@section('title', $metaTitle)
@section('description', $metaDescription)
@section('canonical', url('/pengalaman/'.$requestedSlug))
@section('og_title', $title.' — ANTRABUMI')
@section('og_description', $metaDescription)
@if($metaImage)@section('og_image', $metaImage)@endif

@section('content')
<main class="min-h-screen bg-white">
    <div class="border-b border-neutral-100 bg-neutral-50/80 py-3.5 backdrop-blur-sm"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><nav aria-label="{{ $isEnglish ? 'Breadcrumb' : 'Navigasi jejak' }}" class="flex items-center gap-2 text-xs text-neutral-500"><a href="/" class="transition-colors hover:text-neutral-900">{{ $isEnglish ? 'Home' : 'Beranda' }}</a><span class="text-neutral-300">/</span><a href="/pengalaman" class="transition-colors hover:text-neutral-900">{{ $isEnglish ? 'Experiences' : 'Pengalaman' }}</a><span class="text-neutral-300">/</span><span class="max-w-xs truncate font-medium text-neutral-800 sm:max-w-md">{{ $title }}</span></nav></div></div>

    <section class="relative overflow-hidden border-b border-neutral-100 bg-[#0B1E1A] py-16 text-white sm:py-24"><div class="pointer-events-none absolute inset-0 bg-[radial-gradient(#0D5C4D_1px,transparent_1px)] opacity-10 [background-size:24px_24px]"></div><div class="pointer-events-none absolute right-0 top-0 h-96 w-96 rounded-full bg-[#0D5C4D]/25 blur-3xl"></div><div class="relative z-10 mx-auto w-full max-w-[1280px] space-y-6 px-5 md:px-7 lg:px-10"><div class="flex flex-wrap items-center gap-3"><span class="rounded-full border border-[#147A66] bg-[#0D5C4D] px-3.5 py-1 font-mono text-xs font-semibold text-white">{{ $year ?? ($isEnglish ? 'Experience' : 'Pengalaman') }}</span>@if($category)<span class="rounded-full bg-white/10 px-3.5 py-1 font-mono text-xs font-medium text-neutral-200">{{ $category }}</span>@endif @if($location)<span class="font-mono text-xs text-neutral-300">📍 {{ $location }}</span>@endif @if($clientName)<span class="font-mono text-xs text-neutral-300">· {{ $isEnglish ? 'Partner/Client:' : 'Mitra/Klien:' }} {{ $clientName }}</span>@endif</div><h1 class="max-w-4xl font-heading text-3xl font-bold leading-tight tracking-tight text-white sm:text-4xl lg:text-5xl">{{ $title }}</h1>@if($excerpt)<p class="max-w-4xl text-lg font-light leading-relaxed text-neutral-200 sm:text-xl">{{ $excerpt }}</p>@endif</div></section>

    @if($cover['url'] ?? null)
        <section class="border-b border-neutral-100 bg-neutral-100"><div class="relative mx-auto aspect-[21/9] w-full max-w-[1280px] overflow-hidden"><img src="{{ $cover['url'] }}" alt="{{ $cover['altText'] ?: $title }}" fetchpriority="high" class="h-full w-full object-cover"></div></section>
    @endif

    <section class="bg-white py-14 sm:py-20"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><div class="grid grid-cols-1 gap-12 lg:grid-cols-12">
        <div class="space-y-12 lg:col-span-8">
            @if(count($metrics) > 0)<section><h2 class="mb-4 font-mono text-xs font-semibold uppercase tracking-wider text-neutral-400">{{ $isEnglish ? 'Experience Highlights' : 'Sorotan Pengalaman' }}</h2><div class="grid grid-cols-2 gap-4 sm:grid-cols-3">@foreach($metrics as $metric)<article class="rounded-2xl border border-neutral-100 bg-neutral-50/80 p-5 shadow-sm"><p class="font-heading text-3xl font-bold text-[#0D5C4D]">{{ $metric['value'] }}@if($metric['unit'])<span class="text-lg font-normal text-neutral-600"> {{ $metric['unit'] }}</span>@endif</p><p class="mt-1 text-xs font-medium text-neutral-600">{{ $metric['label'] }}</p></article>@endforeach</div></section>@endif
            @if($description)<section class="space-y-4"><h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-[#0D5C4D]">{{ $isEnglish ? '01 — Overview & Context' : '01 — Gambaran Umum & Konteks' }}</h2><div class="space-y-4 text-base leading-relaxed text-neutral-700">@foreach(preg_split('/\R\R+/', $description) as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>@endif
            @if($methodology)<section class="space-y-4 rounded-2xl border border-neutral-100 bg-neutral-50/50 p-6 sm:p-8"><h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-[#D96B27]">{{ $isEnglish ? '02 — Approach & Methodology' : '02 — Pendekatan & Metodologi' }}</h2><div class="space-y-3 text-sm leading-relaxed text-neutral-700 sm:text-base">@foreach(preg_split('/\R\R+/', $methodology) as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>@endif
            @if($impact)<section class="space-y-4 rounded-2xl border border-[#0D5C4D]/15 bg-[#F5FAF8] p-6 sm:p-8"><h2 class="font-mono text-xs font-semibold uppercase tracking-wider text-[#0D5C4D]">{{ $isEnglish ? '03 — Impact & Outcomes' : '03 — Dampak & Pembelajaran' }}</h2><div class="space-y-3 text-sm leading-relaxed text-neutral-700 sm:text-base">@foreach(preg_split('/\R\R+/', $impact) as $paragraph)<p>{{ $paragraph }}</p>@endforeach</div></section>@endif
            @if($pdf)<section class="pt-2"><div class="group relative overflow-hidden rounded-2xl border border-neutral-200/90 bg-gradient-to-br from-white via-neutral-50/50 to-[#F6FAF8] p-6 shadow-sm transition-all hover:border-[#0D5C4D]/40 hover:shadow-md sm:p-7"><div class="flex flex-col justify-between gap-5 sm:flex-row sm:items-center"><div class="flex items-start gap-4"><div class="flex h-14 w-12 shrink-0 flex-col items-center justify-center rounded-xl bg-gradient-to-b from-red-500 to-red-600 text-white shadow-md shadow-red-500/20"><span class="font-mono text-[10px] font-bold uppercase tracking-wider">PDF</span><span aria-hidden="true" class="mt-0.5">▤</span></div><div class="space-y-1"><span class="rounded bg-[#0D5C4D]/10 px-2 py-0.5 font-mono text-[10px] font-semibold text-[#0D5C4D]">{{ $category ?: ($isEnglish ? 'Official Publication' : 'Dokumen Resmi') }}</span><h2 class="font-heading text-base font-bold text-neutral-900 sm:text-lg">{{ $pdf['originalName'] ?: $title.($isEnglish ? ' (Brief & Case Study)' : ' (Ringkasan & Studi Kasus)') }}</h2><p class="max-w-xl text-xs leading-relaxed text-neutral-600 sm:text-sm">{{ $excerpt ?: ($isEnglish ? 'Official project summary detailing methodology, community participation, and outcomes.' : 'Ringkasan resmi proyek yang memuat metodologi, partisipasi masyarakat, dan capaian lapangan.') }}</p></div></div><div class="flex items-center gap-2.5"><a href="{{ $pdf['url'] }}" target="_blank" rel="noopener noreferrer" class="inline-flex h-10 items-center rounded-xl border border-neutral-300/80 bg-white px-4 text-xs font-semibold text-neutral-800 shadow-sm transition hover:border-[#0D5C4D] hover:bg-[#0D5C4D]/5 hover:text-[#0D5C4D]">{{ $isEnglish ? 'View Document' : 'Lihat Dokumen' }}</a><a href="{{ $pdf['url'] }}" download class="inline-flex h-10 items-center rounded-xl bg-gradient-to-r from-[#0D5C4D] via-[#116958] to-[#147A66] px-5 text-xs font-semibold text-white shadow-sm transition hover:-translate-y-0.5 hover:shadow-md">{{ $isEnglish ? 'Download PDF' : 'Unduh PDF' }}</a></div></div></div></section>@endif
        </div>
        <aside class="space-y-8 lg:col-span-4">
            <section class="space-y-5 rounded-2xl border border-neutral-200/80 bg-neutral-50/60 p-6"><h2 class="font-heading text-sm font-bold uppercase tracking-wider text-neutral-900">{{ $isEnglish ? 'Quick Facts' : 'Informasi Ringkas' }}</h2><dl class="space-y-4 text-xs">@if($year)<div class="flex justify-between border-b border-neutral-200/60 pb-3"><dt class="font-mono text-neutral-500">{{ $isEnglish ? 'Year' : 'Tahun' }}</dt><dd class="font-semibold text-neutral-900">{{ $year }}</dd></div>@endif @if($category)<div class="flex justify-between border-b border-neutral-200/60 pb-3"><dt class="font-mono text-neutral-500">{{ $isEnglish ? 'Category' : 'Kategori' }}</dt><dd class="text-right font-semibold text-neutral-900">{{ $category }}</dd></div>@endif @if($location)<div class="flex justify-between border-b border-neutral-200/60 pb-3"><dt class="font-mono text-neutral-500">{{ $isEnglish ? 'Location' : 'Lokasi' }}</dt><dd class="text-right font-semibold text-neutral-900">{{ $location }}</dd></div>@endif @if($clientName)<div class="flex justify-between border-b border-neutral-200/60 pb-3"><dt class="font-mono text-neutral-500">{{ $isEnglish ? 'Partner' : 'Mitra/Klien' }}</dt><dd class="text-right font-semibold text-neutral-900">{{ $clientName }}</dd></div>@endif</dl><a href="/kolaborasi" class="inline-flex w-full items-center justify-center gap-2 rounded-xl bg-[#0D5C4D] px-4 py-2.5 text-xs font-semibold text-white shadow-sm transition hover:bg-[#116958]">{{ $isEnglish ? 'Collaborate on a Project' : 'Ajukan Kolaborasi' }} →</a></section>
            <section class="space-y-3 rounded-2xl border border-neutral-200/80 bg-white p-6"><p class="font-mono text-[10px] font-bold uppercase tracking-wider text-[#0D5C4D]">{{ $isEnglish ? 'ANTRABUMI WORKING FRAMEWORK' : 'CARA KERJA ANTRABUMI' }}</p><p class="font-heading text-xs font-bold text-neutral-900">{{ $isEnglish ? '01 LISTEN · 02 CONNECT · 03 CO-CREATE · 04 ACT · 05 LEARN' : '01 DENGARKAN · 02 HUBUNGKAN · 03 RANCANG BERSAMA · 04 BERTINDAK · 05 BELAJAR' }}</p><p class="text-xs leading-relaxed text-neutral-500">{{ $isEnglish ? '“Every collaboration begins with understanding context, not offering solutions.”' : '“Setiap kolaborasi dimulai dari memahami konteks, bukan menawarkan solusi.”' }}</p></section>
            <a href="/pengalaman" class="inline-flex items-center gap-2 text-xs font-semibold text-[#0D5C4D] hover:underline">← {{ $isEnglish ? 'Back to all experiences' : 'Kembali ke semua pengalaman' }}</a>
        </aside>
    </div></div></section>

    @if(count($otherExperiences) > 0)<section class="border-t border-neutral-100 bg-neutral-50/50 py-14 sm:py-18"><div class="mx-auto w-full max-w-[1280px] px-5 md:px-7 lg:px-10"><div class="mb-8 flex items-center justify-between"><div><p class="font-mono text-xs font-bold uppercase tracking-widest text-[#0D5C4D]">{{ $isEnglish ? 'Other Experiences' : 'Pengalaman Lainnya' }}</p><h2 class="mt-1 font-heading text-xl font-bold text-neutral-950">{{ $isEnglish ? 'Explore more field experiences' : 'Jelajahi pengalaman lapangan lainnya' }}</h2></div><a href="/pengalaman" class="hidden text-xs font-semibold text-[#0D5C4D] hover:underline sm:inline-block">{{ $isEnglish ? 'View all →' : 'Lihat semua →' }}</a></div><div class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">@foreach($otherExperiences as $other)<a href="/pengalaman/{{ $other['slug'] }}" class="group flex flex-col justify-between rounded-2xl border border-neutral-200/80 bg-white p-6 shadow-sm transition hover:-translate-y-1 hover:border-[#0D5C4D]/30 hover:shadow-md"><div><div class="mb-2 flex items-center justify-between font-mono text-xs text-neutral-400"><span class="font-bold text-[#0D5C4D]">{{ $other['category'] }}</span><span>{{ $other['year'] }}</span></div><h3 class="line-clamp-2 font-heading text-base font-bold text-neutral-900 transition-colors group-hover:text-[#0D5C4D]">{{ $other['title'] }}</h3><p class="mt-2 line-clamp-2 text-xs leading-relaxed text-neutral-500">{{ $other['excerpt'] }}</p></div><div class="mt-4 flex items-center gap-1 text-xs font-semibold text-[#0D5C4D]">{{ $isEnglish ? 'Read details' : 'Lihat selengkapnya' }} →</div></a>@endforeach</div></div></section>@endif
</main>
@endsection