@php
    $shareUrl = url('/pengetahuan/'.$slug);
    $shareText = trim(($title ?? '').(empty($text) ? '' : "\n\n".$text));
    $encodedUrl = rawurlencode($shareUrl);
    $encodedTitle = rawurlencode($title ?? '');
    $encodedText = rawurlencode($shareText);
@endphp
<section class="border-t border-neutral-100 bg-white py-8 sm:py-10">
    <div class="mx-auto w-full max-w-[760px] px-5 md:px-7 lg:px-10"><div class="rounded-2xl border border-neutral-200/80 bg-neutral-50/70 p-4 sm:p-5"><div class="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><p class="text-xs font-semibold uppercase tracking-wider text-neutral-700">{{ $label }}</p><p data-share-feedback role="status" class="text-xs font-medium text-[#0D5C4D]" aria-live="polite"></p></div><div class="mt-3 grid grid-cols-2 gap-2 sm:flex sm:flex-wrap"><a target="_blank" rel="noopener noreferrer" href="https://wa.me/?text={{ $encodedText }}%20{{ $encodedUrl }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-[#25D366] px-3 py-2 text-xs font-semibold text-white transition hover:brightness-95">WhatsApp</a><a target="_blank" rel="noopener noreferrer" href="https://www.facebook.com/sharer/sharer.php?u={{ $encodedUrl }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-[#1877F2] px-3 py-2 text-xs font-semibold text-white transition hover:brightness-95">Facebook</a><a target="_blank" rel="noopener noreferrer" href="https://www.linkedin.com/sharing/share-offsite/?url={{ $encodedUrl }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-[#0A66C2] px-3 py-2 text-xs font-semibold text-white transition hover:brightness-95">LinkedIn</a><a target="_blank" rel="noopener noreferrer" href="https://twitter.com/intent/tweet?url={{ $encodedUrl }}&amp;text={{ $encodedTitle }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-neutral-900 px-3 py-2 text-xs font-semibold text-white transition hover:bg-neutral-700">X / Twitter</a><button type="button" data-share-instagram data-share-url="{{ $shareUrl }}" class="inline-flex min-h-10 items-center justify-center rounded-lg bg-gradient-to-r from-[#833AB4] via-[#E1306C] to-[#F77737] px-3 py-2 text-xs font-semibold text-white transition hover:brightness-95">Instagram</button><button type="button" data-share-copy data-share-url="{{ $shareUrl }}" class="inline-flex min-h-10 items-center justify-center rounded-lg border border-neutral-300 bg-white px-3 py-2 text-xs font-semibold text-neutral-700 transition hover:border-neutral-900 hover:text-neutral-900">{{ $isEnglish ? 'Copy Link' : 'Salin Link' }}</button></div></div></div>
</section>